ContosoUniversity/Models/InstructorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ContosoUniversity.Models
{
    public class InstructorViewModel
    {
        public int? Id { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        [StringLength(50)]
        public string LastName { get; set; }

        [Required]
        [Column("FirstName")]
        [Display(Name = "First Name")]
        [StringLength(50)]
        public string FirstName { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Hire Date")]
        public DateTime? HireDate { get; set; }

        [Display(Name = "Full Name")]
        public string FullName
        {
            get { return LastName + ", " + FirstName; }
        }

        public IEnumerable<CourseViewModel> Courses { get; set; }
        public OfficeAssignmentViewModel OfficeAssignment { get; set; }
    }
}

ContosoUniversity/Controllers/InstructorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ContosoUniversity.Models;
using AutoMapper.QueryableExtensions;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Net;
using AutoMapper;
using Data.Domain;

namespace ContosoUniversity.Controllers
{
    public class InstructorController : BaseController
    {
        #region Index        
        public ActionResult Index(int? id, Guid? courseId)
        {
            var viewModel = new InstructorDataViewModel();
            viewModel.Instructors = DbContext.Instructors
                                    .OrderBy(i => i.LastName)
                                    .ProjectTo<InstructorViewModel>() // AutoMapper will be automatically use Include method to load related data while mapping
                                    .ToList();

            if (id != null)
            {
                ViewBag.InstructorID = id.Value;
                viewModel.Courses = viewModel.Instructors.Single(i => i.Id == id.Value).Courses;
            }

            if (courseId != null)
            {
                ViewBag.CourseID = courseId.Value;
                viewModel.Enrollments = viewModel.Courses.Single(x => x.Id == courseId).Enrollments;
                // Explicit loading Enrollments
                // DbContext.Entry(course).Collection(x => x.Enrollments).Load();
                // DbContext.Entry(enrollment).Reference(x => x.Student).Load();
            }

            return View(viewModel);
        }
        #endregion

        #region Edit (Get)
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var instructor = DbContext.Instructors
               .Include(i => i.OfficeAssignment)
               .Include(i => i.Courses)
               .Single(i => i.Id == id);

            var vm = Mapper.Map<InstructorViewModel>(instructor);
            PopulateAssignedCourseData(instructor);

            if (vm == null)
            {
                return HttpNotFound();
            }

            return View(vm);
        }
        #endregion


        #region Edit (Post)
        /*
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,LastName,FirstName,HireDate,OfficeAssignment")]InstructorViewModel vm)
        {
            if (vm.Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var oldInstructor = DbContext.Instructors
               .Include(i => i.OfficeAssignment)
               .Single(i => i.Id == vm.Id);

            var newInstructor = Mapper.Map<Instructor>(vm);

            try
            {
                if (string.IsNullOrWhiteSpace(newInstructor.OfficeAssignment.Location))
                {
                    newInstructor.OfficeAssignment = null;
                }

                DbContext.Entry(oldInstructor).CurrentValues.SetValues(newInstructor);
                DbContext.Entry(oldInstructor).State = EntityState.Modified;

                DbContext.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (RetryLimitExceededException)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }

            return View(newInstructor);
        }
        */

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id, string[] selectedCourses)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var instructorToUpdate = DbContext.Instructors
              .Include(i => i.OfficeAssignment)
              .Include(i => i.Courses)
              .Single(i => i.Id == id);

            // TryUpdateModel: model binder from FormCollection to instructorToUpdate entity
            if (TryUpdateModel(instructorToUpdate, "", new string[] { "LastName", "FirstName", "HireDate", "OfficeAssignment" }))
            {
                try
                {
                    if (string.IsNullOrWhiteSpace(instructorToUpdate.OfficeAssignment.Location))
                    {
                        instructorToUpdate.OfficeAssignment = null;
                    }

                    UpdateInstructorCourses(selectedCourses, instructorToUpdate);

                    DbContext.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }

            PopulateAssignedCourseData(instructorToUpdate);
            return View(instructorToUpdate);
        }
        #endregion

        #region Course
        private void PopulateAssignedCourseData(Instructor instructor)
        {
            var allCourses = DbContext.Courses;
            var instructorCourses = new HashSet<Guid>(instructor.Courses.Select(c => c.Id));
            var viewModel = new List<AssignedCourseDataViewModel>();
            foreach (var course in allCourses)
            {
                viewModel.Add(new AssignedCourseDataViewModel
                {
                    CourseId = course.Id,
                    Title = course.Title,
                    Assigned = instructorCourses.Contains(course.Id)
                });
            }
            ViewBag.Courses = viewModel;
        }

        private void UpdateInstructorCourses(string[] selectedCourses, Instructor instructorToUpdate)
        {
            if (selectedCourses == null)
            {
                instructorToUpdate.Courses = new List<Course>();
                return;
            }

            var selectedCoursesHS = new HashSet<string>(selectedCourses);
            var instructorCourses = new HashSet<Guid>(instructorToUpdate.Courses.Select(c => c.Id));

            foreach (var course in DbContext.Courses)
            {
                if (selectedCoursesHS.Contains(course.Id.ToString()))
                {
                    if (!instructorCourses.Contains(course.Id))
                    {
                        instructorToUpdate.Courses.Add(course);
                    }
                }
                else
                {
                    if (instructorCourses.Contains(course.Id))
                    {
                        instructorToUpdate.Courses.Remove(course);
                    }
                }
            }
        }
        #endregion
    }
}

ContosoUniversity/Views/Instructor/Edit.cshtml
@model ContosoUniversity.Models.InstructorViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Instructor"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Course</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HireDate, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.HireDate)
                @Html.ValidationMessageFor(model => model.HireDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OfficeAssignment, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OfficeAssignment.Location)
                @Html.ValidationMessageFor(model => model.OfficeAssignment.Location)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <table>
                    <tr>
                        @{
                            int cnt = 0;
                            List<ContosoUniversity.Models.AssignedCourseDataViewModel> courses = ViewBag.Courses;

                            foreach (var course in courses)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @:<td>
                                    <input type="checkbox"
                                           name="selectedCourses"
                                           value="@course.CourseId"
                                           @(Html.Raw(course.Assigned ? "checked=\"checked\"" : "")) />
                                    @course.CourseId @:@course.Title
                                    @:</td>
                            }
                            @:</tr>
                        }
                    </table>
                </div>
            </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContosoUniversity/Views/Instructor/Index.cshtml
@model ContosoUniversity.Models.InstructorDataViewModel

@{
    ViewBag.Title = "Instructors";
}

<h2>Instructors</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Hire Date</th>
        <th>Office</th>
        <th>Courses</th>
        <th></th>
    </tr>

    @foreach (var item in Model.Instructors)
    {
        string selectedRow = "";
        if (item.Id == ViewBag.InstructorID)
        {
            selectedRow = "success";
        }
        <tr class="@selectedRow">
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HireDate)
            </td>
            <td>
                @if (item.OfficeAssignment != null)
                {
                    @item.OfficeAssignment.Location
                }
            </td>
            <td>
                @{
                    foreach (var course in item.Courses)
                    {
                        @course.Id @:  @course.Title <br />
                    }
                }
            </td>
            <td>
                @Html.ActionLink("Select", "Index", new {id = item.Id}) |
                @Html.ActionLink("Edit", "Edit", new {id = item.Id}) |
                @Html.ActionLink("Details", "Details", new {id = item.Id}) |
                @Html.ActionLink("Delete", "Delete", new {id = item.Id})
            </td>
        </tr>
    }
</table>

@if (Model.Courses != null)
{
    <h3>Courses Taught by Selected Instructor</h3>
    <table class="table">
        <tr>
            <th></th>
            <th>Number</th>
            <th>Title</th>
            <th>Department</th>
        </tr>

        @foreach (var item in Model.Courses)
        {
            string selectedRow = "";
            if (item.Id == ViewBag.CourseID)
            {
                selectedRow = "success";
            }
            <tr class="@selectedRow">
                <td>
                    @Html.ActionLink("Select", "Index", new { courseId = item.Id })
                </td>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Title
                </td>
                <td>
                    @item.Department.Name
                </td>
            </tr>
        }
    </table>
}

@if (Model.Enrollments != null)
{
    <h3>
        Students Enrolled in Selected Course
    </h3>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Grade</th>
        </tr>
        @foreach (var item in Model.Enrollments)
        {
            <tr>
                <td>
                    @item.Student.FullName
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Grade)
                </td>
            </tr>
        }
    </table>
}